name: Build and Deploy to Cloud Run

on:
  push:
    branches: ["master", "coba-deploy"]

env:
  PROJECT_ID: sehatinaja-c7205
  GAR_LOCATION: asia-southeast2
  SERVICE: sehatinaja
  REGION: asia-southeast2
  IMAGE_NAME: gcr.io/sehatinaja-c7205/sehatinaja
  FIREBASESERVICEACCOUNT: ${{ secrets.FIREBASESERVICEACCOUNT }}
  MY_ENV: ${{ secrets.MY_ENV}}

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GH_ACTIONS_KEY }}"

      - name: Copy firebase service account
        env:
          FIREBASESERVICEACCOUNT: ${{ secrets.FIREBASESERVICEACCOUNT}}
        run: cp $FIREBASESERVICEACCOUNT app/credentials/firebaseServiceAccount.json

      - name: Copy .env file
        run: cp ${{ env.MY_ENV }} app/.env

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.IMAGE_NAME }}:${{ github.sha }}" ./
          docker tag "${{ env.IMAGE_NAME }}:${{ github.sha }}" "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker push "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Remove Credentials Folder
        run: rm -rf credentials/

      - name: Remove .env file
        run: rm .env

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
